[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test/'

solc_version    = '0.8.18'       # Override for the solc version (setting this ignores `auto_detect_solc`)
optimizer       = true           # Enable or disable the solc optimizer
optimizer_runs  = 20000            # The number of optimizer runs (the higher the number the more optimized for runtime the code will be generated)
# verbosity       = 3              # The verbosity of tests
fs_permissions = [{ access = "read", path = "./"}]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config


# See more config options https://github.com/foundry-rs/foundry/tree/master/config